/**
 * generate-guide.js
 *
 * Reads all results/ JSON files produced by the discovery scripts and
 * synthesizes a comprehensive ESPN-API-GUIDE.md at the project root.
 *
 * Sections:
 *   1. Header + run metadata
 *   2. Authentication
 *   3. Base endpoints (from endpoints-interesting.json)
 *   4. View parameters (baseline + discovered views + schemas)
 *   5. X-Fantasy-Filter (discovered keys + value probes)
 *   6. Response schemas (per-view field listings)
 *   7. Historical data (boundaries, per-season degradation)
 *   8. Quick reference (copy-paste curl + JS snippets)
 *
 * Each section guards against missing files — you can run a subset of
 * discovery scripts and still generate a partial guide.
 *
 * Usage:  node src/report/generate-guide.js
 *    or:  npm run guide
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import config from '../config.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..', '..');
const resultsDir = join(root, 'results');
const outPath = join(root, 'ESPN-API-GUIDE.md');

// ── Helpers ───────────────────────────────────────────────────────────────────

function readResult(filename) {
  const fp = join(resultsDir, filename);
  if (!existsSync(fp)) return null;
  try {
    return JSON.parse(readFileSync(fp, 'utf8'));
  } catch {
    return null;
  }
}

function lastModified(filename) {
  const fp = join(resultsDir, filename);
  if (!existsSync(fp)) return null;
  return statSync(fp).mtime.toISOString().slice(0, 16).replace('T', ' ');
}

/** Pad a markdown table row */
function row(...cells) {
  return `| ${cells.join(' | ')} |`;
}

/** Markdown table header + divider */
function tableHeader(...cols) {
  return [
    row(...cols),
    row(...cols.map(() => '---')),
  ].join('\n');
}

/** Format a JS fetch snippet for a given URL + options */
function fetchSnippet(url, { view, filter, description } = {}) {
  const lines = [];
  lines.push('```js');
  if (filter) {
    lines.push(`const filter = ${JSON.stringify(filter, null, 2)};`);
    lines.push('');
  }
  lines.push(`const res = await fetch('${url}', {`);
  lines.push(`  headers: {`);
  lines.push(`    'Accept': 'application/json',`);
  if (filter) lines.push(`    'X-Fantasy-Filter': JSON.stringify(filter),`);
  lines.push(`    // 'Cookie': 'espn_s2=...; SWID=...',  // add for private leagues`);
  lines.push(`  },`);
  lines.push(`});`);
  lines.push(`const data = await res.json();`);
  lines.push('```');
  return lines.join('\n');
}

function curlSnippet(url, { filter } = {}) {
  const lines = [`curl '${url}' \\`, `  -H 'Accept: application/json' \\`];
  if (filter) lines.push(`  -H 'X-Fantasy-Filter: ${JSON.stringify(filter)}' \\`);
  lines.push(`  # -H 'Cookie: espn_s2=...; SWID=...'  # add for private leagues`);
  return '```bash\n' + lines.join('\n') + '\n```';
}

// ── Section builders ──────────────────────────────────────────────────────────

function buildHeader() {
  const lines = [];
  lines.push('# ESPN Fantasy Football API — Comprehensive Guide');
  lines.push('');
  lines.push('> Auto-generated by the [espn-api-discovery](https://github.com/yourusername/espn-api-discovery) toolkit.');
  lines.push('> Re-run `node src/report/generate-guide.js` to refresh after running discovery scripts.');
  lines.push('');

  const meta = [];
  meta.push(`| Field | Value |`);
  meta.push(`| --- | --- |`);
  meta.push(`| Season | ${config.season} |`);
  meta.push(`| League ID | ${config.leagueId || '*(not set)*'} |`);
  meta.push(`| Auth | ${config.isAuthenticated ? '✓ Authenticated (espn_s2 + SWID set)' : '✗ Public only'} |`);
  meta.push(`| Generated | ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC |`);

  const files = ['baseline-summary.json', 'views-summary.json', 'filters-summary.json',
    'endpoints-interesting.json', 'history-report.json', 'schema-index.json'];
  for (const f of files) {
    const ts = lastModified(f);
    if (ts) meta.push(`| \`${f}\` | Last run: ${ts} |`);
  }

  lines.push(...meta);
  lines.push('');
  return lines.join('\n');
}

function buildAuth() {
  return `## Authentication

The ESPN Fantasy API uses two browser cookies for private league access.

| Cookie | Where to find it | Required for |
| --- | --- | --- |
| \`espn_s2\` | Browser DevTools → Application → Cookies → \`fantasy.espn.com\` | Private league endpoints |
| \`SWID\` | Same location (format: \`{GUID}\`) | Private league endpoints |

**Without cookies:** Players endpoints and some public data still work. You just won't be able to query private leagues.

**Getting your cookies:**
1. Log in to [fantasy.espn.com](https://fantasy.espn.com)
2. Open DevTools (\`F12\`) → **Application** tab → **Cookies** → \`https://fantasy.espn.com\`
3. Copy \`espn_s2\` and \`SWID\` values into your \`.env\`

**Using cookies in requests:**
\`\`\`js
const res = await fetch(url, {
  headers: {
    'Cookie': \`espn_s2=\${process.env.ESPN_S2}; SWID=\${process.env.SWID}\`,
  },
});
\`\`\`

`;
}

function buildEndpoints() {
  const data = readResult('endpoints-interesting.json');
  const all = readResult('endpoints-all.json');

  const lines = [];
  lines.push('## Base Endpoints');
  lines.push('');

  if (!data) {
    lines.push('*Run `node src/discovery/endpoints.js` to populate this section.*');
    lines.push('');
    return lines.join('\n');
  }

  lines.push(`Found **${data.length}** responding endpoints across ${all?.length ?? '?'} probed.\n`);

  // Group by section
  const sections = {};
  for (const ep of data) {
    const s = ep.section || 'other';
    if (!sections[s]) sections[s] = [];
    sections[s].push(ep);
  }

  for (const [section, eps] of Object.entries(sections)) {
    const title = section.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
    lines.push(`### ${title}`);
    lines.push('');
    lines.push(tableHeader('Label', 'Top-Level Keys', 'Notes'));
    for (const ep of eps) {
      const keys = ep.topLevelKeys?.join(', ') || '—';
      const url = ep.url || '';
      lines.push(row(`\`${ep.label}\``, keys, url ? `[URL](${url})` : ''));
    }
    lines.push('');
  }

  // Segments detail
  const segments = data.filter((e) => e.section === 'segments');
  if (segments.length > 0) {
    lines.push('### Segment Behavior');
    lines.push('');
    lines.push(tableHeader('Segment', 'HTTP Status', 'Keys'));
    for (const s of (all || []).filter((e) => e.section === 'segments').sort((a, b) => a.segment - b.segment)) {
      lines.push(row(`\`${s.segment}\``, String(s.status), s.topLevelKeys?.join(', ') || '—'));
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildViews() {
  const baseline = readResult('baseline-summary.json');
  const viewsResult = readResult('views-summary.json');
  const schemaIndex = readResult('schema-index.json');

  const lines = [];
  lines.push('## View Parameters');
  lines.push('');
  lines.push('Views are requested via the `view` query parameter. Multiple views can be combined:');
  lines.push('```');
  lines.push('?view=mTeam&view=mRoster&view=mMatchup');
  lines.push('```');
  lines.push('');

  if (!baseline && !viewsResult) {
    lines.push('*Run `node src/discovery/baseline.js` and `node src/discovery/views.js` to populate this section.*');
    lines.push('');
    return lines.join('\n');
  }

  // Merge known + discovered views into one master list
  const allViews = [];

  if (baseline) {
    for (const v of baseline) {
      allViews.push({
        name: v.view,
        status: v.changedFromBaseline ? '✓ working' : '~ no-op',
        origin: 'known',
        keysAdded: v.newKeysBeyondBaseline || [],
        httpStatus: v.status,
      });
    }
  }

  if (viewsResult?.discovered) {
    for (const v of viewsResult.discovered) {
      // Don't double-add if already in baseline
      if (!allViews.find((a) => a.name === v.view)) {
        allViews.push({
          name: v.view,
          status: '✨ newly discovered',
          origin: 'discovered',
          keysAdded: v.keysAdded || [],
          httpStatus: v.status,
          sizeChange: v.sizeChangedBy,
        });
      }
    }
  }

  // Master table
  lines.push('### All Views');
  lines.push('');
  lines.push(tableHeader('View', 'Status', 'Origin', 'Keys Added', 'Fields'));
  for (const v of allViews) {
    const schemaInfo = schemaIndex?.[v.name];
    const fieldCount = schemaInfo?.totalFields ?? '—';
    const keys = v.keysAdded.length ? v.keysAdded.map((k) => `\`${k}\``).join(', ') : '—';
    lines.push(row(`\`${v.name}\``, v.status, v.origin, keys, String(fieldCount)));
  }
  lines.push('');

  // Per-view detail for working views
  const working = allViews.filter((v) => v.status !== '~ no-op' && v.httpStatus === 200);
  if (working.length > 0) {
    lines.push('### View Details & Usage');
    lines.push('');

    for (const v of working) {
      lines.push(`#### \`${v.name}\``);
      if (v.origin === 'discovered') lines.push('> ✨ **Newly discovered by this toolkit**');
      lines.push('');

      // Field list from schema diff
      const diff = readResult(`schema-diff-baseline-vs-${v.name}.json`);
      const uniqueFields = diff?.[`only_in_${v.name}`] || [];
      if (uniqueFields.length > 0) {
        lines.push(`**Unique fields (not in baseline):** ${uniqueFields.length}`);
        lines.push('');
        // Show first 20 unique fields to keep guide readable
        const sample = uniqueFields.slice(0, 20);
        for (const f of sample) lines.push(`- \`${f}\``);
        if (uniqueFields.length > 20) lines.push(`- *...and ${uniqueFields.length - 20} more (see \`results/schema-diff-baseline-vs-${v.name}.json\`)*`);
        lines.push('');
      }

      const leagueUrl = `https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${config.season}/segments/0/leagues/{LEAGUE_ID}?view=${v.name}`;
      lines.push(fetchSnippet(leagueUrl, { view: v.name }));
      lines.push('');
    }
  }

  // Stats on no-ops and errors
  const noOp = viewsResult?.noOp || [];
  const errors = viewsResult?.errors || [];
  if (noOp.length > 0) {
    lines.push('### No-Op Views (same response as no view)');
    lines.push('');
    lines.push('These views return HTTP 200 but the response is identical to making no view request:');
    lines.push('');
    lines.push(noOp.map((v) => `\`${v}\``).join(', '));
    lines.push('');
  }

  if (errors.length > 0) {
    lines.push('### Invalid View Names (returned errors)');
    lines.push('');
    lines.push(tableHeader('View', 'HTTP Status'));
    for (const e of errors) lines.push(row(`\`${e.view}\``, String(e.status)));
    lines.push('');
  }

  return lines.join('\n');
}

function buildFilters() {
  const summary = readResult('filters-summary.json');
  const probes = readResult('filters-value-probes.json');

  const lines = [];
  lines.push('## X-Fantasy-Filter Header');
  lines.push('');
  lines.push('The `X-Fantasy-Filter` request header accepts a JSON object to filter, sort, and paginate results.');
  lines.push('It\'s most impactful on the **players endpoint** but also works on the league endpoint.');
  lines.push('');
  lines.push('**Basic usage:**');
  lines.push('```js');
  lines.push('const filter = { filterActive: { value: true }, limit: 50, offset: 0 };');
  lines.push("headers['X-Fantasy-Filter'] = JSON.stringify(filter);");
  lines.push('```');
  lines.push('');

  if (!summary) {
    lines.push('*Run `node src/discovery/filters.js` to populate this section.*');
    lines.push('');
    return lines.join('\n');
  }

  const discovered = summary.discovered || [];
  const noOp = summary.noOp || [];
  const errors = summary.errors || [];

  lines.push(`### Discovered Filter Keys (${discovered.length} working)`);
  lines.push('');

  if (discovered.length === 0) {
    lines.push('No new filter keys discovered beyond the known baseline.');
  } else {
    // Build value probe columns
    const probeLabels = probes
      ? Object.values(probes)[0]?.map((p) => p.probe) || []
      : [];

    if (probeLabels.length > 0) {
      lines.push(tableHeader('Key', 'Works On', ...probeLabels));
      for (const d of discovered) {
        const where = [d.playersChanged ? 'players' : null, d.leagueChanged ? 'league' : null]
          .filter(Boolean).join('+') || '—';
        const probeCols = probeLabels.map((label) => {
          const probe = probes?.[d.key]?.find((p) => p.probe === label);
          if (!probe) return '—';
          return probe.changed ? '✓' : (probe.status !== 200 ? '✗' : '~');
        });
        lines.push(row(`\`${d.key}\``, where, ...probeCols));
      }
    } else {
      lines.push(tableHeader('Key', 'Works On'));
      for (const d of discovered) {
        const where = [d.playersChanged ? 'players' : null, d.leagueChanged ? 'league' : null]
          .filter(Boolean).join('+') || '—';
        lines.push(row(`\`${d.key}\``, where));
      }
    }
    lines.push('');
    lines.push('> ✓ = changes response · ~ = accepted but no visible change · ✗ = rejected/error');
    lines.push('');
  }

  // Known baseline keys
  lines.push('### Known Filter Keys (community-documented baseline)');
  lines.push('');
  lines.push(tableHeader('Key', 'Common Usage'));
  const knownKeys = [
    ['filterActive', 'Filter to active players: `{"value": true}`'],
    ['filterStatus', 'Filter by player status string'],
    ['filterSlotIds', 'Filter by roster slot IDs: `{"values": [0, 2, 4]}`'],
    ['filterRanksForScoringPeriodIds', 'Ranks for a specific scoring period'],
    ['filterRanksForRankTypes', 'Rank type (STANDARD, PPR, etc.)'],
    ['sortPercOwned', 'Sort by ownership %: `{"sortPriority": 1, "sortAsc": false}`'],
    ['sortDraftRanks', 'Sort by draft rank'],
    ['limit', 'Max results to return (default 50, max ~1000)'],
    ['offset', 'Pagination offset'],
  ];
  for (const [k, usage] of knownKeys) lines.push(row(`\`${k}\``, usage));
  lines.push('');

  // Practical examples
  lines.push('### Practical Filter Examples');
  lines.push('');
  lines.push('**Get all active players (paginated):**');
  lines.push('```js');
  lines.push('const filter = {');
  lines.push('  filterActive: { value: true },');
  lines.push('  limit: 50,');
  lines.push('  offset: 0,  // increment by 50 for each page');
  lines.push('};');
  lines.push('```');
  lines.push('');
  lines.push('**Get all players sorted by ownership:**');
  lines.push('```js');
  lines.push('const filter = {');
  lines.push('  filterActive: { value: true },');
  lines.push('  sortPercOwned: { sortPriority: 1, sortAsc: false },');
  lines.push('  limit: 300,');
  lines.push('};');
  lines.push('```');
  lines.push('');
  lines.push('**Filter to specific roster slots (QB=0, RB=2, WR=4, TE=6, K=17, D/ST=16):**');
  lines.push('```js');
  lines.push('const filter = {');
  lines.push('  filterSlotIds: { values: [0, 2, 4] },  // QB, RB, WR only');
  lines.push('  limit: 200,');
  lines.push('};');
  lines.push('```');
  lines.push('');

  if (noOp.length > 0) {
    lines.push(`### No-Op Keys (${noOp.length} — accepted but don't change response)`);
    lines.push('');
    lines.push(noOp.map((k) => `\`${k}\``).join(', '));
    lines.push('');
  }

  return lines.join('\n');
}

function buildSchemas() {
  const schemaIndex = readResult('schema-index.json');

  const lines = [];
  lines.push('## Response Schemas');
  lines.push('');
  lines.push('Recursively extracted field schemas for each view. Arrays show the type of the first element.');
  lines.push('');

  if (!schemaIndex) {
    lines.push('*Run `node src/discovery/schemas.js` to populate this section.*');
    lines.push('');
    return lines.join('\n');
  }

  // Summary table
  lines.push('### Schema Overview');
  lines.push('');
  lines.push(tableHeader('View', 'Top-Level Keys', 'Total Fields', 'Schema File'));
  for (const [view, info] of Object.entries(schemaIndex)) {
    if (!info) { lines.push(row(`\`${view}\``, '—', '—', 'fetch failed')); continue; }
    const keys = info.topLevelKeys?.map((k) => `\`${k}\``).join(', ') || '—';
    const file = `results/schema-${view}.json`;
    lines.push(row(`\`${view}\``, keys, String(info.totalFields ?? '—'), `\`${file}\``));
  }
  lines.push('');

  // Per-view flat field listing (capped to avoid huge output)
  lines.push('### Field Listings by View');
  lines.push('');
  lines.push('> Full schemas saved to `results/schema-{view}.json`. Showing first 50 fields per view.');
  lines.push('');

  for (const [view] of Object.entries(schemaIndex)) {
    const schema = readResult(`schema-${view}.json`);
    if (!schema?.flat) continue;

    const flat = schema.flat;
    const entries = Object.entries(flat);

    lines.push(`<details>`);
    lines.push(`<summary><strong><code>${view}</code></strong> — ${entries.length} fields</summary>`);
    lines.push('');
    lines.push(tableHeader('Field Path', 'Type'));
    for (const [path, type] of entries.slice(0, 50)) {
      lines.push(row(`\`${path}\``, String(type)));
    }
    if (entries.length > 50) {
      lines.push(row(`*...${entries.length - 50} more fields*`, ''));
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  return lines.join('\n');
}

function buildHistory() {
  const report = readResult('history-report.json');

  const lines = [];
  lines.push('## Historical Data');
  lines.push('');

  if (!report) {
    lines.push('*Run `node src/discovery/history.js` to populate this section.*');
    lines.push('');
    return lines.join('\n');
  }

  lines.push('### Oldest Accessible Seasons');
  lines.push('');
  lines.push(tableHeader('Endpoint Type', 'Oldest Season', 'Notes'));
  lines.push(row('Players endpoint (public)', String(report.oldestPlayersSeason ?? '—'), 'No auth required'));
  lines.push(row('League endpoint (private)', String(report.oldestLeagueSeason ?? '—'), 'Requires espn_s2 + SWID'));
  lines.push('');

  // Per-season breakdown
  if (report.seasonBreakdown?.length > 0) {
    lines.push('### Per-Season View Availability');
    lines.push('');

    // Get all unique view names tested
    const allViews = [...new Set(
      report.seasonBreakdown.flatMap((s) => [...s.workingViews, ...s.brokenViews])
    )];

    lines.push(tableHeader('Season', ...allViews));
    for (const season of report.seasonBreakdown) {
      const cols = allViews.map((v) =>
        season.workingViews.includes(v) ? '✓' : (season.brokenViews.includes(v) ? '✗' : '—')
      );
      lines.push(row(String(season.season), ...cols));
    }
    lines.push('');
    lines.push('> ✓ = view returns data · ✗ = view fails or returns empty');
    lines.push('');
  }

  // leagueHistory endpoint
  const histData = report.leagueHistoryEndpoint;
  if (histData && Object.keys(histData).length > 0) {
    lines.push('### leagueHistory Endpoint');
    lines.push('');
    lines.push(`URL: \`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/leagueHistory/{LEAGUE_ID}?seasonId={YEAR}\``);
    lines.push('');
    lines.push(tableHeader('Season', 'HTTP Status', 'Has Data', 'Top-Level Keys'));
    for (const [year, info] of Object.entries(histData).sort((a, b) => b[0] - a[0])) {
      const keys = info.topKeys?.join(', ') || '—';
      lines.push(row(year, String(info.status), info.hasData ? '✓' : '✗', keys));
    }
    lines.push('');
  }

  // Players boundary
  if (report.playersBoundary?.length > 0) {
    lines.push('### Players Endpoint Year-by-Year');
    lines.push('');
    lines.push(tableHeader('Season', 'HTTP Status', 'Players Returned'));
    for (const p of report.playersBoundary) {
      lines.push(row(String(p.year), String(p.status), String(p.playerCount ?? '—')));
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildQuickReference() {
  const lines = [];
  lines.push('## Quick Reference');
  lines.push('');
  lines.push('Copy-paste ready snippets. Replace `{LEAGUE_ID}` and `{SEASON}` with your values.');
  lines.push('');

  const season = config.season;
  const leagueUrl = `https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${season}/segments/0/leagues/{LEAGUE_ID}`;
  const playersUrl = `https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${season}/players`;
  const historyUrl = `https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/leagueHistory/{LEAGUE_ID}`;
  const proTeamsUrl = `https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${season}/proTeams`;

  lines.push('### League Data');
  lines.push('');
  lines.push('**Get team + roster data:**');
  lines.push(curlSnippet(`${leagueUrl}?view=mTeam&view=mRoster`));
  lines.push('');
  lines.push('**Get full matchup + box score:**');
  lines.push(curlSnippet(`${leagueUrl}?view=mMatchup&view=mBoxscore`));
  lines.push('');
  lines.push('**Get league settings:**');
  lines.push(curlSnippet(`${leagueUrl}?view=mSettings`));
  lines.push('');
  lines.push('**Get draft results:**');
  lines.push(curlSnippet(`${leagueUrl}?view=mDraftDetail`));
  lines.push('');
  lines.push('**Get live scoring:**');
  lines.push(curlSnippet(`${leagueUrl}?view=mLiveScoring&view=mMatchup`));
  lines.push('');

  lines.push('### Player Data');
  lines.push('');
  lines.push('**Get top 300 players by ownership:**');
  lines.push(curlSnippet(
    `${playersUrl}?view=kona_player_info`,
    { filter: { filterActive: { value: true }, sortPercOwned: { sortPriority: 1, sortAsc: false }, limit: 300 } }
  ));
  lines.push('');
  lines.push('**Get all active players (paginated):**');
  lines.push('```js');
  lines.push(`const BASE = '${playersUrl}';`);
  lines.push('const allPlayers = [];');
  lines.push('let offset = 0;');
  lines.push('while (true) {');
  lines.push('  const filter = { filterActive: { value: true }, limit: 50, offset };');
  lines.push('  const res = await fetch(`${BASE}?view=kona_player_info`, {');
  lines.push("    headers: { 'X-Fantasy-Filter': JSON.stringify(filter) },");
  lines.push('  });');
  lines.push('  const data = await res.json();');
  lines.push('  if (!data.length) break;');
  lines.push('  allPlayers.push(...data);');
  lines.push('  offset += 50;');
  lines.push('}');
  lines.push('```');
  lines.push('');

  lines.push('### Historical Data');
  lines.push('');
  lines.push('**Get historical season data:**');
  lines.push(curlSnippet(`${historyUrl}?seasonId=2020&view=mSettings`));
  lines.push('');

  lines.push('### Pro Teams');
  lines.push('');
  lines.push('**Get NFL team info:**');
  lines.push(curlSnippet(proTeamsUrl));
  lines.push('');

  lines.push('### JS Utility Function');
  lines.push('');
  lines.push('```js');
  lines.push('async function espn(path, { views = [], filter = null, season = 2024, leagueId } = {}) {');
  lines.push(`  const base = 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl';`);
  lines.push('  const url = new URL(`${base}${path}`);');
  lines.push('  if (season) url.searchParams.set(\'seasonId\', season);');
  lines.push('  for (const v of views) url.searchParams.append(\'view\', v);');
  lines.push('  const headers = { Accept: \'application/json\' };');
  lines.push('  if (filter) headers[\'X-Fantasy-Filter\'] = JSON.stringify(filter);');
  lines.push('  if (process.env.ESPN_S2) headers.Cookie = `espn_s2=${process.env.ESPN_S2}; SWID=${process.env.SWID}`;');
  lines.push('  const res = await fetch(url.toString(), { headers });');
  lines.push('  return res.json();');
  lines.push('}');
  lines.push('');
  lines.push('// Usage:');
  lines.push(`const teams = await espn(\`/seasons/2024/segments/0/leagues/\${LEAGUE_ID}\`, {`);
  lines.push('  views: [\'mTeam\', \'mRoster\'],');
  lines.push('});');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

// ── Main ──────────────────────────────────────────────────────────────────────

function run() {
  console.log('Generating ESPN-API-GUIDE.md...\n');

  const sections = [
    { name: 'Header',           fn: buildHeader },
    { name: 'Authentication',   fn: buildAuth },
    { name: 'Base Endpoints',   fn: buildEndpoints },
    { name: 'View Parameters',  fn: buildViews },
    { name: 'X-Fantasy-Filter', fn: buildFilters },
    { name: 'Response Schemas', fn: buildSchemas },
    { name: 'Historical Data',  fn: buildHistory },
    { name: 'Quick Reference',  fn: buildQuickReference },
  ];

  const parts = [];
  for (const { name, fn } of sections) {
    process.stdout.write(`  ${name.padEnd(22)}`);
    try {
      const content = fn();
      parts.push(content);
      console.log('✓');
    } catch (err) {
      console.log(`✗ (${err.message})`);
      parts.push(`## ${name}\n\n*Error generating section: ${err.message}*\n\n`);
    }
  }

  const guide = parts.join('\n---\n\n');
  writeFileSync(outPath, guide);

  const lines = guide.split('\n').length;
  const kb = Math.round(Buffer.byteLength(guide, 'utf8') / 1024);
  console.log(`\nWrote ESPN-API-GUIDE.md — ${lines} lines, ${kb} KB`);
  console.log(`Path: ${outPath}`);
}

run();
